# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 84ad01aa37d5f82d8d422bd2793451c1c0da83587712359fdbb8f09eca06e73f7fd0dbfc5c8048883ef664dd8195c301b444d7e597e4c048f1f82e8b39aed2e9

test:
  secret_key_base: 271d6069995a6beec1a3ecd71538f9e1652125f12281e856c6fe1bdef95ca9587794d1542a560ad72a015ab2adb4eef8093b5a1d50f10d1aa6ac01655c6561a0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
